[package]
name = "meh-asus"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.67"

[dev-dependencies]
anyhow = "1.0.92"
libc = { version = "0.2.161" }
notify-rust = { version = "4.11.3" }
